overtimeRecorder/urls.py
from django.urls import path, include

from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name="overtime"
urlpatterns = [
    #extension /tracker
    path('', views.Index, name='index'),
    path("user/<int:pk>/", views.UserDetailsView, name="userDetails"),
    path("newuser/", views.CreateNewUser, name="createNewUser"),
    path("updateuser/", views.EditUser, name="updateUser"),
    path("request/<int:pk>/", views.detailOvertimeRowView, name="requestRow"),
    path("print/", views.printOptions, name="printViewOptions"),
    path("print/<int:pk>/", views.printView, name="printView"),
    path("runprint/this_paycycle/", views.createMostRecentPayCyclePrintout, name="create_this_paycycle"),
    path("runprint/custom/", views.createCustomPayCyclePrintout, name="create_custom_paycycle"),
    path("changeDetails/<int:pk>/", views.changeDetails, name="changeDetails"),
    path("print/<int:pk>/", views.printView, name="printView"),
    path("roster/", views.inputRoster, name="rosterInput"),
    path("roster/<int:pk>", views.editIndividualRosterItem, name="editRosterItem"),
    path("inptovertime/", views.inputOvertime, name="overtimeReq"),
    path("inptovertime/<date>/", views.inputOvertimeJustDate, name="overtimeReqWDate"),
    path("inptovertime/<date>/<time>/", views.inputOvertime, name="overtimeReqWDateAndTime"),
    path("inptovertime/<date>/<time>/<int:AfterNotBefore>", views.inputOvertime, name="overtimeReqWDateAndTime"),
    path("accounts/", include('django.contrib.auth.urls')),
    path("post/ajax/overtime/", views.submitAjaxOvertimeForm, name="ajaxOvertime"),
    path("post/ajax/overtimeDelete/", views.submitAjaxOvertimeFormDelete, name="ajaxOvertimeDelete"),
    path("post/ajax/createCalendar", views.createCalendar, name="createCalendar"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

overtimeTracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('overtimeRecorder.urls')),
    path('admin/', admin.site.urls),
]

overtimeRecorder/forms.py
from django import forms
from .models import OvertimeRow, Profile, Roster
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
col_control = 'form-control col-sm-6'

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = col_control
        self.fields["email"].widget.attrs["readonly"] = True
        self.fields["email"].help_text = "this is linked to your username and isn't editable. Please contact admin if you need this changed"

class CreateNewUserForm(UserCreationForm):
    first_name= forms.CharField()
    last_name= forms.CharField()
    email= forms.CharField()
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
    def __init__(self, *args, **kwargs):
        super(CreateNewUserForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = col_control
        

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('employeeNumber','classification', 'department', 'payCycle', 'okToShareRoster', 'okToShareOvertime')
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = col_control


class OvertimeRowForm(forms.ModelForm):
    class Meta:
        model = OvertimeRow
        fields = ('date', 'reason', 'patientURN','startTime', 'finishTime', 'higherDutiesYN','preApproval','personalComment')
    
    
    def __init__(self, *args, **kwargs):
        super(OvertimeRowForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = col_control
            
    widgets = {
        "startTime": forms.TimeInput(format='%H:%M'),
        "finishTime": forms.TimeInput(format='%H:%M')
    }

class OvertimeRowFormShortened(forms.ModelForm):
    class Meta:
        model = OvertimeRow
        fields = ('date', 'reason', 'patientURN','startTime', 'finishTime','personalComment')
        
    def __init__(self, *args, **kwargs):
        super(OvertimeRowFormShortened, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = col_control

class OvertimeRowFormSuperShortened(forms.Form):
    CLINICAL_REASONS = (
        ('', "Reason") ,
        (1, "Direct Patient Care or Theatre") ,
        (2, "WR or Delayed/Extended handover (no URN)"),
        (3, "Discharge Summaries or Patient Admin"),
        (4, "MDM preparation"),
    )
    reason = forms.ChoiceField(label="Reason for overtime", choices=CLINICAL_REASONS, required=False)
    patientURN = forms.CharField(label="Patient URN", max_length=20, required=False)
    arriveEarly = forms.TimeField(label="Early time", required=False)
    leaveLate = forms.TimeField(label="Late time", required=False)
    date = forms.DateField(widget=forms.HiddenInput(), required=False)
    def __init__(self, *args, **kwargs):
        super(OvertimeRowFormSuperShortened, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control-sm form-control small-form-css col'
            visible.field.widget.attrs['placeholder'] = visible.field.label


class RosterForm(forms.Form):
    rosterField = forms.CharField(label="Your Roster", widget=forms.Textarea)

class RosterIndForm(forms.ModelForm):
    class Meta:
        model = Roster
        fields = ('startDateTime', 'endDateTime', 'role','job', 'oncallTF')
        
    def __init__(self, *args, **kwargs):
        super(RosterIndForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = col_control

class CustomPayCycleForm(forms.Form):
    startDate = forms.DateField(label="starting date")
    finishDate = forms.DateField(label="ending date")
    
    def __init__(self, *args, **kwargs):
        super(CustomPayCycleForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = col_control


class DeleteForm(forms.ModelForm):
    class Meta:
        model = OvertimeRow
        fields = ('date',)
        widgets = {"date": forms.HiddenInput()}

overtimeRecorder/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import re
import math
import json
import uuid
import os

from django.shortcuts import render, get_object_or_404
from django.template import loader
from .models import OvertimeRow, PrintOutTimeSheet, Roster, CalendarFile
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from django.views import generic
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib import messages
from .forms import UserForm, ProfileForm, OvertimeRowForm, RosterForm, OvertimeRowFormShortened, CreateNewUserForm, RosterIndForm, OvertimeRowFormSuperShortened, CustomPayCycleForm, DeleteForm
import datetime
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import JsonResponse
from django.core import serializers
from django.core import files
from django.core.files import File
from django.utils import timezone
from django.core.files.temp import NamedTemporaryFile


def Index(request):
    if request.user.is_authenticated:
        recent_roster = Roster.objects.filter(user = request.user, startDateTime__lte=datetime.datetime.now() + datetime.timedelta(days=1), startDateTime__gte=datetime.datetime.now() - datetime.timedelta(days=14)).order_by('endDateTime')
        recent_overtime = OvertimeRow.objects.filter(user = request.user, date__lte=datetime.date.today(), date__gte=datetime.date.today() - datetime.timedelta(days=14)).order_by('date')
        if recent_overtime.count() >= 1:
            filterOvertime = True
        else:
            filterOvertime = False
        if recent_roster.count() >= 1:
            filterRoster = True
        else:
            filterRoster = False
        recent_roster_and_overtime_View = []
        for i in range(14):
            single_day = []
            dateToTest = datetime.date.today() - datetime.timedelta(days=i)
            single_day.append(dateToTest)
            if filterRoster:
                day_roster = recent_roster.filter(startDateTime__year=dateToTest.year,startDateTime__month=dateToTest.month,startDateTime__day=dateToTest.day)

                if day_roster.count() >= 1:
                    single_day.append(day_roster)
                else:
                    single_day.append("")
            else:
                single_day.append("")
            overtime_array = []
            if filterOvertime:
                day_overtime = recent_overtime.filter(date=dateToTest)
                if day_overtime.count() >= 1:
                    dateOvertimeArray = []
                    for item in range(day_overtime.count()):
                        delete_form = DeleteForm(instance=day_overtime[item], prefix=day_overtime[item].pk)
                        dateOvertimeArray.append([day_overtime[item],delete_form])
                    overtime_array.append(dateOvertimeArray)
                    
                    form = OvertimeRowFormSuperShortened(prefix=dateToTest.strftime("%Y%m%d"), initial={'date':dateToTest})
                else:
                    overtime_array.append("")
                    form =""
            else:
                form=""
      
                
            overtime_array.append(form)
            single_day.append(overtime_array)

            recent_roster_and_overtime_View.append(single_day)
                    
        future_roster = Roster.objects.filter(user = request.user, endDateTime__gte=datetime.datetime.now()).order_by('endDateTime')[:7]
        recent_overtime_sheets = PrintOutTimeSheet.objects.filter(user = request.user).order_by('created_at')[:5]
    
        context = {
            'recent_roster' :recent_roster,
            'future_roster': future_roster,
            'recent_overtime_sheets': recent_overtime_sheets,
            "recent_roster_and_overtime_View":recent_roster_and_overtime_View,
        }
        return render(request, "overtimeRecorder/index.html", context)
    else:
        return render(request, "overtimeRecorder/homepage.html")

@login_required
def UserDetailsView(request, pk):
    return HttpResponse("you're viewing user %s" % pk)


def CreateNewUser(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/accounts/logout?next=' + reverse('overtime:createNewUser'))
    else:
        if request.method == 'POST':  
            user_form = CreateNewUserForm(request.POST)
            if user_form.is_valid():  
                obj = user_form.save(commit=False)
                obj.username = obj.email
                obj.save()
                profile_update = ProfileForm(request.POST, instance=obj.profile)
                profile_update.is_valid()
                profile_update.save()
                messages.success(request, 'Account created successfully')  
                return HttpResponseRedirect(reverse('overtime:login')) 
            else:
            
                return HttpResponseRedirect(reverse('overtime:index')) 
        
        else:  
            A_date_array=[]
            B_date_array=[]
            A_counter = datetime.date(2022, 1, 2)
            B_counter = datetime.date(2022, 1, 9)
            while A_counter < datetime.date.today() - datetime.timedelta(days=30):
                A_counter += datetime.timedelta(days=14)
            while B_counter < datetime.date.today() - datetime.timedelta(days=30):
                B_counter += datetime.timedelta(days=14)

            while len(A_date_array) < 5:
                A_date_array.append(A_counter)
                A_counter += datetime.timedelta(days=14)
            while len(B_date_array) < 5:
                B_date_array.append(B_counter)
                B_counter += datetime.timedelta(days=14)

            user_form = CreateNewUserForm()
            profile_form = ProfileForm()
            context = {  
                'user_form': user_form,
                'profile_form': profile_form,
                "A_date_array": A_date_array,
                "B_date_array": B_date_array
            }  
            return render(request, 'overtimeRecorder/register.html', context)  

@login_required
def EditUser(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, ('Your profile was successfully updated!'))
            return HttpResponseRedirect(reverse('overtime:index'))
        else:
            messages.error(request, ('Please correct the error below.'))
    else:
            user_form = UserForm(instance=request.user)
            profile_form = ProfileForm(instance=request.user.profile)
    A_date_array=[]
    B_date_array=[]
    A_counter = datetime.date(2022, 1, 2)
    B_counter = datetime.date(2022, 1, 9)
    while A_counter < datetime.date.today() - datetime.timedelta(days=30):
        A_counter += datetime.timedelta(days=14)
    while B_counter < datetime.date.today() - datetime.timedelta(days=30):
        B_counter += datetime.timedelta(days=14)

    while len(A_date_array) < 5:
        A_date_array.append(A_counter)
        A_counter += datetime.timedelta(days=14)
    while len(B_date_array) < 5:
        B_date_array.append(B_counter)
        B_counter += datetime.timedelta(days=14)


    return render(request, 'overtimeRecorder/profile.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        "A_date_array": A_date_array,
        "B_date_array": B_date_array
    })
    
@login_required
def detailOvertimeRowView(request, pk):
    row = get_object_or_404(OvertimeRow,pk=pk)
    if request.method == "POST":
        row_form = OvertimeRowForm(request.POST, instance=row)
        if row_form.is_valid():
            row_form.save()
            messages.success(request, "Overtime information successfully updated!")
            return HttpResponseRedirect(reverse('overtime:index'))
        else:
            messages.error(request, ('Please correct the error below.'))
            form = OvertimeRowForm(instance=row)
            return render(request, "overtimeRecorder/detailView.html", {"row":row, "form": form})
    else:
        form = OvertimeRowForm(instance=row)
        return render(request, "overtimeRecorder/detailView.html", {"row":row, "form": form})

@login_required
def printOptions(request):
    if request.method == "POST":
        row_form = CustomPayCycleForm(request.POST)
        if row_form.is_valid():
            rows = OvertimeRow.objects.filter(
                Q(user=request.user),Q(date__lte=row_form.cleaned_data['finishDate']), Q(date__gte=row_form.cleaned_data['startDate'])
            )
            printout = PrintOutTimeSheet(user=request.user, startDate=row_form.cleaned_data['startDate'], endingDate=row_form.cleaned_data['finishDate'] )
            printout.save()
            for row in rows:
                printout.linkedOvertimeRows.add(row)
            return HttpResponseRedirect(reverse('overtime:printView', args=(printout.id,)))
        else:
            messages.error(request, ('Please correct the error below.'))
            form = CustomPayCycleForm(instance=row_form)
            return render(request, "overtimeRecorder/overtimePrintOptions.html", { "form": form})
    else:
        form = CustomPayCycleForm()
        recent_overtime_sheets = PrintOutTimeSheet.objects.filter(user = request.user).order_by('created_at')[:5]
        return render(request, "overtimeRecorder/overtimePrintOptions.html", {
            "form":form,
            "recent_overtime_sheets":recent_overtime_sheets,
        })

@login_required
def createMostRecentPayCyclePrintout(request):
    rows = OvertimeRow.objects.filter(

overtimeRecorder/templates/overtimeRecorder/detailView.html
{% extends './template.html' %}

{% block title%}Detailed View{% endblock  %}

{% block content %}
    <div class="form-wrapper">
        <div class="form-title"><h3>Edit Overtime</h3></div>
        <div class="form-content">
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group row">
                    {{field.errors}}
                    <label class="col-sm-2 col-form-label" for="id_{{ field.name }}">{{ field.label }}</label>
                    {% comment %} {{field}}  {% endcomment %}

                    {{field}}
                    {% if field.help_text %}
                        <div class="form-text-div">
                            <small class="form-text text-muted col-sm-12 offset-sm-2 form-help-text">{{ field.help_text }}</small>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
            <button class="btn btn-primary" type="submit">Save changes</button>
        </form>
    </div>
        </div>
{% comment %}     
    <form action="{% url 'overtime:changeDetails' row.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>overtime request</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            
            <input type="text" name="patientURN" id="patientURN" value="{{ row.patientURN }}">
            <label for="patientURN">patientURN</label><br>
            
        </fieldset>
        <input type="submit" value="Save">
        </form> {% endcomment %}

{% endblock %}

overtimeRecorder/templates/overtimeRecorder/homepage.html
{% extends './template.html' %}

{% block title%}Homepage{% endblock  %}

{% block content %}
{% load static %}
    <div class="content-wrapper">
        <h3>Welcome</h3>
        <p>Welcome to the home page of the RMH overtime sheet submission website.</p>
        <p>This was designed for you to be able to quickly submit and record overtime</p>
    </div>
{% endblock%}

overtimeRecorder/templates/overtimeRecorder/index.html
{% extends './template.html' %}

{% block title%}Index{% endblock  %}

{% block content %}
    {% load static %}
    <div class="content-wrapper">
        <div class="Roster future content-block">
            <div class="title future">
                <div>
                <div><h4>Future Roster</h4></div>
                <div>
                    <button id="createCalendar">Add the next 7 days to my calendar</button>
                </div>
            </div>
            </div>
            <div class"roster_content">
                {% if future_roster %}
                
                    {% for row in future_roster %}
                        <div class="future RosterRow">
                            <div class="to_left">
                                <div class="day">
                                    <span>{{row.startDateTime|date:"D"}}</span>
                                </div>
                                <div class="date">
                                    <span class="date">{{row.startDateTime|date:"dS"}}</span>
                                    <span class="month">{{row.startDateTime|date:"N"}}</span>
                                </div>
                            </div>
                            <div class='to_right'>
                                <span class="firstRow">{{row.startDateTime|date:"g:i a"}} - {{row.endDateTime|date:'g:i a (d/m)'}}  <a href="{% url 'overtime:editRosterItem' row.pk %}">edit</a></span>
                                <span class="secondRow">{% if row.oncallTF %}<strong>On-call</strong> {% endif %}{{row.role}}: {{row.job}}</span>
                            </div>
                        </div>
                    {% endfor %}
                
                {% else %}
                    <p>No rows are available.</p>
                {% endif %}
            </div>
        </div>
        
        <div class="Roster recent content-block">
            <div class="title recent"><h4>Recent Roster and Overtime</h4></div>
            <div class"roster_content">
                {% if recent_roster_and_overtime_View %}
                    
                    {% for row in recent_roster_and_overtime_View %}
                        <div class="rosterOvertimeRow" id="{{row.0|date:"Ymd"}}">
                            <div class="to_left">
                                <div class="day">
                                    <span>{{row.0|date:"D"}}</span>
                                </div>
                                <div class="date">
                                    <span class="date">{{row.0|date:"dS"}}</span>
                                    <span class="month">{{row.0|date:"N"}}</span>
                                </div>
                            </div>
                            <div class='to_right rosterAndOvertime'>
                                <div class="firstColumn">
                                    {% if row.1 %}
                                        {% for item in row.1%}    
                                            <span class="firstRow">{{item.startDateTime|date:"g:i a"}} - {{item.endDateTime|date:'g:i a (d/m)'}}  <a href="{% url 'overtime:overtimeReqWDateAndTime' date=item.endDateTime|date:'d-m-Y' time=item.endDateTime|date:'G:i' %}">full overtime form</a></span>
                                            <span class="secondRow">{% if item.oncallTF %}<strong>On-call</strong> {% endif %}{{item.role}}: {{item.job}}</span>
                                        {% endfor %}
                                    {% else %}<span>No work <a href="{% url 'overtime:overtimeReqWDate' date=row.0|date:'d-m-Y'%}">overtime form...</a></span>{% endif %}
                                </div>
                                <div class="secondColumn">
                                    <div class="firstrow">
                                        {% if row.2.0 %}
                                            {% for item in row.2.0%}
                                                <span class="currentOvertimeRequests" id="{{item.0.id}}">
                                                    {{item.0.startTime}}-{{item.0.finishTime}} ({{item.0.get_reason_display}}{%if item.0.patientURN%}:#{{item.0.patientURN}}{% endif %})
                                                        <a href="{% url 'overtime:requestRow' item.0.pk %}">edit</a>
                                                        <form class="deleteOvertimeForm">
                                                            {% csrf_token%}
                                                            {{item.1}}
                                                            <button class="inline-btn" type="submit">delete</button>
                                                        </form>
                                                </span>
                                            {% endfor%}
                                        {% else %}<span class="currentOvertimeRequests muted">No overtime recorded</span>{% endif %}

                                    </div>
                                    <div class="secondrow">
                                        {% if row.2.1 %}
                                        <form class="overtimeForm">
                                            {% csrf_token %}
                                            <div class="row row-no-margin">
                                                {% for field in row.2.1%}
                                                    {{field}}
                                                {% endfor %}
                                                <button class="btn btn-primary btn-small col-1" type="submit">Save</button>
                                            </div> 
                                        </form> 
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
            
                {% else %}
                    <p>No rows are available.</p>
                {% endif %}
            </div>
        </div>
        


        <div class="overtimeSheets content-block">
            <div class="title overtime-print"><h4>Recently printed overtime sheets</h4></div>
            {% if recent_overtime_sheets %}
            <ol>
                {% for row in recent_overtime_sheets %}
                <li><a href="{% url 'overtime:printView' row.pk %}">{{ row.startDate }} - {{ row.endingDate }}</a></li>
                {% endfor %}
            </ol>
            {% else %}
                <p>No rows are available.</p>
            {% endif %}
        <div>
    </div>

    <script src="{% static "overtimeRecorder/index.js"%}?{% now "U" %}">
{% endblock%}

overtimeRecorder/templates/overtimeRecorder/overtimePrintOptions.html
{% extends './template.html' %}

{% block title%}Homepage{% endblock  %}

{% block content %}
    <div class="content-wrapper">
    <div class="content-block">
        <h4>Overtime print options</h4>
        <p>This page is designed to let you chose what overtime printout you would like.</p>
        <p>Please pick from the following options.</p>
        <div class="title thisPaycycle">
            <h4>Print overtime for this most recent paycycle</h4>
        </div>
            <a href="{% url 'overtime:create_this_paycycle'%}"><p>Click this text to create your overtime form for this paycycle</p></a>
    </div>

    <div class="form-wrapper">
        <div class="form-title title customPaycycle"><h4>Custom Overtime Paycycle</h4></div>
        <div class="form-content">
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group row">
                    {{field.errors}}
                    <label class="col-sm-2 col-form-label" for="id_{{ field.name }}">{{ field.label }}</label>
                    {% comment %} {{field}}  {% endcomment %}

                    {{field}}
                    {% if field.help_text %}
                        <div class="form-text-div">
                            <small class="form-text text-muted col-sm-12 offset-sm-2 form-help-text">{{ field.help_text }}</small>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
               
            <button class="btn btn-primary" type="submit">Create</button>
        </form>
        </div>
    </div>
    <div class="overtimeSheets content-block">
        <div class="title overtime-print"><h4>Recently printed overtime sheets</h4></div>
        {% if recent_overtime_sheets %}
        <ol>
            {% for row in recent_overtime_sheets %}
            <li><a href="{% url 'overtime:printView' row.pk %}">{{ row.startDate }} - {{ row.endingDate }}</a></li>
            {% endfor %}
        </ol>
        {% else %}
            <p>No rows are available.</p>
        {% endif %}
    <div>


    
    </div>
{% endblock%}

overtimeRecorder/templates/overtimeRecorder/template.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title%}{% endblock%} - overtime Tracker</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "/overtimeRecorder/style.css"%}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  </head>
  <body>
    {% comment %} NAVBAR {% endcomment %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'overtime:index' %}">Overtime Tracker</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'overtime:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'overtime:overtimeReq' %}">Input overtime</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'overtime:printViewOptions' %}">Print overtime form</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'overtime:rosterInput' %}">Add Roster</a>
            </li>
          </ul>
        </div>
        {% if user.is_authenticated%}
          <span class="navbar-text">
             {{ user.username }}
          </span>
          <a class="nav-link" href="{% url 'overtime:updateUser' %}">Profile</a>
          <a class="nav-link" href="{% url 'overtime:logout' %}">Log Out</a>
          
          
        {% else %}
    
            <a class="nav-link" href="{% url 'overtime:login' %}">Log in</a>
          
          
            <a class="nav-link" href="{% url 'overtime:createNewUser' %}">Sign up</a>
          
        {% endif%}
      </div>
    </nav>
    {% if messages %}  
    <ul>   
        {% for message in messages %}  
            <li>{{ message }}</li>  
            {% endfor %}  
    </ul>   
    {% endif %}  
    <div class='content'>
      {% block content%}
      
      {% endblock%}
    </div>

    {% comment %} <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> {% endcomment %}
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script async src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block scripts%}{% endblock%}
  </body>
</html>